### ISSUE TITLE
Todo für die Abgabe

### ISSUE THREAD

**Issue by NerdyStuff** [Grimmig18/doodle-classifier#1]
- [x] Quickdraw Package Credit geben
- [x] Erklären was ein CNN
- [x] Wie ist das Dataset aufgebaut
- [x] Verkackte Versuche zeigen, falls möglich
- [ ] Code Kommentieren
- [x] Präsentation erstellen
- [x] Dataprocessing Progress darstellen
- [x] Verbesserung der Klassifizierung darstellen
- [x] Weitere Parameter für den Lernprozess testen
